### PR TITLE
add summary for endpoints

### PR DESCRIPTION
**Pull request by ableeb**

### CODE REVIEW

**Comment by svx** [comment]
@ableeb Looks awesome!!! 
Quick question, why do we use `\u301c` aka tilde ?
Do we want a line break here?
😄 

Screenshot 2020-06-03 at 08 34 56

**Comment by ableeb** [comment]
yeah thats weird maybe a typo?

**Comment by svx** [comment]
I think it has to do with the syntax:https://github.com/onna/open-api/pull/6/files#diff-81a4213b3282d6ebe982e56a204421caR1703 (one example, see the the unicode there?)

I can try with a realtime swagger editor session, later - Or we merge and fix with the next release ?

**Comment by ableeb** [comment]
yeah something to do with the description let me poke at this a little here

**Comment by ableeb** [comment]
@svx the `~` comes from Guillotina's swagger processing

**Comment by svx** [comment]
UH :( !  - :) Does it would make sense to change/fix that? @vangheem what do you think?

**Comment by ableeb** [comment]
@svx we can control it in the service definition, fixing now

**Comment by svx** [comment]
@ableeb you are awesome!!!

**Pull request merged**
